extra_css:
  - stylesheets/extra.css
site_name: ECG Info
site_url: https://eagle57f.github.io/ECG1_Info/
nav:
  - 1ère année:
    - Accueil: 1ere/index.md

    - Cours :
        - 1 - Bases du Python : 1ere/TP1.md
        - 2 - Boucles for et while, tests : 1ere/TP2.md
        - 3 - Listes : 1ere/TP3.md
        - 4 - Fonctions : 1ere/TP4.md
        - 5 - Matrices avec Numpy : 1ere/TP5.md
        - 6 - Graphiques avec Matplotlib : 1ere/TP6.md
    - Exercices: 1ere/Exercices.md
    - Corrections et PDF des TP :
      - TP1 : 1ere/Exercices_TP1.md
      - TP2 : 1ere/Exercices_TP2.md
      - TP3 : 1ere/Exercices_TP3.md
      - TP4 : 1ere/Exercices_TP4.md
      - TP5 : 1ere/Exercices_TP5.md
      - TP6 : 1ere/Exercices_TP6.md
    - Corrections des DS :
      - DS 2024 : 1ere/Correction_DS_2024.md
      - Correction DS 2025 : 1ere/Correction_DS_2025.md
    - Ressources :
        - Programme officiel (PDF) : 1ere/Ressources-Exercices-Corrections\Ressources\Programme officiel d'informatique.pdf
        - Toutes les fonctions de 1ère année : 1ere/Toutes_les_fonctions_de_1ere_annee.md
  - 2ème année:
    - Accueil: 2eme/index.md
    - Correction des TP:
      - Feuille 1 : 2eme/Feuille1/Feuille1.md
      - Feuille 2 : 2eme/Feuille2/Feuille2.md
      - Feuille 3 : 2eme/Feuille3/Feuille3.md
    - Ressources:
      - Mémo Python : 2eme/Ressources/Memo_Python.pdf
    - DS:
      - DS1 2024 : 2eme/DS/DS1_2024.md
      - DS1 2023 : 2eme/DS/DS1_2023.md


theme:
  variant: modern
  icon:
    logo: simple/python
  favicon: favicon64.png
  language: fr
  footer:
    social: true

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Passer en mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: lucide/moon
        name: Passer en mode clair

  features:
    - content.hide.title
    - palette.toggle
    - content.code.copy
    - content.code.annotate
    # - navigation.expand
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
  highlightjs: false
  

plugins:
  - search


extra:
  generator: true
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/Eagle57f
    name: Mon GitHub
  - icon: fontawesome/solid/envelope
    link: mailto:eagle57f@gmail.com
    name: Me contacter


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js